### ISSUE TITLE
I found some incompatibility..

### ISSUE THREAD

**Issue by ghost** [joseph-montanez/raylib-php#5]
Hi, I'm trying your framework with php and linux mint. 
I am sad to say raylib release a new version, the 3.5, and there's a couple of incompatibilities with your framework. I was able to quick fix but I think some funcions would be redefinied or deleted because the changelog of november is about 150 lines of added / deleted functionalities.
Finally I was able, after a quick fix on code, to compile the .so library and start build a game, but still, some functions are not working perfectly.
Good work btw!

Greetings from Italy.

**Comment by joseph-montanez** [comment]
@ricky89 Thanks for your interest. I am closing this for #8 as its a bit more clear what needs to be done. Progress can be tracked there.
